[flake8]
ignore =
    W503  # Line break before binary operator - Conflicts black
    E203  # Whitespace before ':' - Conflicts black
    A003  # class attribute is shadowing a python builtin - Pointless: https://github.com/gforcada/flake8-builtins/issues/75
max-line-length = 122
max-complexity = 10
import-order-style = smarkets
statistics = True
count = True
verbose = 1
enable-extensions = G
